/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FollowersRouteImport } from './routes/followers'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FocusReposRouteImport } from './routes/focus/repos'
import { Route as FocusMineRouteImport } from './routes/focus/mine'
import { Route as BindGithubRouteImport } from './routes/bind/github'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReposRouteImport } from './routes/admin/repos'
import { Route as AdminPublicReleasesRouteImport } from './routes/admin/public-releases'
import { Route as AdminJobsRouteRouteImport } from './routes/admin/jobs/route'
import { Route as FocusReposIndexRouteImport } from './routes/focus/repos/index'
import { Route as FocusMineIndexRouteImport } from './routes/focus/mine/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as FocusReposReleasesRouteImport } from './routes/focus/repos/releases'
import { Route as FocusOrgOrgRouteImport } from './routes/focus/org/$org'
import { Route as FocusMineReleasesRouteImport } from './routes/focus/mine/releases'
import { Route as AdminJobsTranslationsRouteImport } from './routes/admin/jobs/translations'
import { Route as AdminJobsSubscriptionsRouteImport } from './routes/admin/jobs/subscriptions'
import { Route as AdminJobsScheduledRouteImport } from './routes/admin/jobs/scheduled'
import { Route as AdminJobsLlmRouteImport } from './routes/admin/jobs/llm'
import { Route as OwnerRepoReleasesRouteImport } from './routes/$owner/$repo/releases'
import { Route as FocusOrgOrgIndexRouteImport } from './routes/focus/org/$org/index'
import { Route as OwnerRepoReleasesIndexRouteImport } from './routes/$owner/$repo/releases/index'
import { Route as FocusRepoOwnerRepoRouteImport } from './routes/focus/repo/$owner/$repo'
import { Route as FocusOrgOrgReleasesRouteImport } from './routes/focus/org/$org/releases'
import { Route as AdminJobsSubscriptionsTaskIdRouteImport } from './routes/admin/jobs/subscriptions/$taskId'
import { Route as AdminJobsTasksTaskIdRouteRouteImport } from './routes/admin/jobs/tasks/$taskId/route'
import { Route as FocusRepoOwnerRepoIndexRouteImport } from './routes/focus/repo/$owner/$repo/index'
import { Route as AdminJobsTasksTaskIdIndexRouteImport } from './routes/admin/jobs/tasks/$taskId/index'
import { Route as FocusRepoOwnerRepoReleasesRouteImport } from './routes/focus/repo/$owner/$repo/releases'
import { Route as OwnerRepoReleasesTagTagRouteImport } from './routes/$owner/$repo/releases/tag/$tag'
import { Route as PublicOwnerRepoReleasesTagTagRouteImport } from './routes/public/$owner/$repo/releases/tag/$tag'
import { Route as AdminJobsTasksTaskIdLlmCallIdRouteImport } from './routes/admin/jobs/tasks/$taskId/llm/$callId'

const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/stars.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/releases.lazy').then((d) => d.Route))
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/inbox.lazy').then((d) => d.Route))
const FollowersRoute = FollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/followers.lazy').then((d) => d.Route))
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/briefs.lazy').then((d) => d.Route))
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const FocusReposRoute = FocusReposRouteImport.update({
  id: '/focus/repos',
  path: '/focus/repos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/focus/repos.lazy').then((d) => d.Route))
const FocusMineRoute = FocusMineRouteImport.update({
  id: '/focus/mine',
  path: '/focus/mine',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/focus/mine.lazy').then((d) => d.Route))
const BindGithubRoute = BindGithubRouteImport.update({
  id: '/bind/github',
  path: '/bind/github',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bind/github.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/users.lazy').then((d) => d.Route))
const AdminReposRoute = AdminReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/repos.lazy').then((d) => d.Route))
const AdminPublicReleasesRoute = AdminPublicReleasesRouteImport.update({
  id: '/public-releases',
  path: '/public-releases',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/public-releases.lazy').then((d) => d.Route),
)
const AdminJobsRouteRoute = AdminJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FocusReposIndexRoute = FocusReposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FocusReposRoute,
} as any).lazy(() =>
  import('./routes/focus/repos/index.lazy').then((d) => d.Route),
)
const FocusMineIndexRoute = FocusMineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FocusMineRoute,
} as any).lazy(() =>
  import('./routes/focus/mine/index.lazy').then((d) => d.Route),
)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/index.lazy').then((d) => d.Route),
)
const FocusReposReleasesRoute = FocusReposReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => FocusReposRoute,
} as any).lazy(() =>
  import('./routes/focus/repos/releases.lazy').then((d) => d.Route),
)
const FocusOrgOrgRoute = FocusOrgOrgRouteImport.update({
  id: '/focus/org/$org',
  path: '/focus/org/$org',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/focus/org/$org.lazy').then((d) => d.Route),
)
const FocusMineReleasesRoute = FocusMineReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => FocusMineRoute,
} as any).lazy(() =>
  import('./routes/focus/mine/releases.lazy').then((d) => d.Route),
)
const AdminJobsTranslationsRoute = AdminJobsTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/translations.lazy').then((d) => d.Route),
)
const AdminJobsSubscriptionsRoute = AdminJobsSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/subscriptions.lazy').then((d) => d.Route),
)
const AdminJobsScheduledRoute = AdminJobsScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/scheduled.lazy').then((d) => d.Route),
)
const AdminJobsLlmRoute = AdminJobsLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/llm.lazy').then((d) => d.Route),
)
const OwnerRepoReleasesRoute = OwnerRepoReleasesRouteImport.update({
  id: '/$owner/$repo/releases',
  path: '/$owner/$repo/releases',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$owner/$repo/releases.lazy').then((d) => d.Route),
)
const FocusOrgOrgIndexRoute = FocusOrgOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FocusOrgOrgRoute,
} as any).lazy(() =>
  import('./routes/focus/org/$org/index.lazy').then((d) => d.Route),
)
const OwnerRepoReleasesIndexRoute = OwnerRepoReleasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoReleasesRoute,
} as any).lazy(() =>
  import('./routes/$owner/$repo/releases/index.lazy').then((d) => d.Route),
)
const FocusRepoOwnerRepoRoute = FocusRepoOwnerRepoRouteImport.update({
  id: '/focus/repo/$owner/$repo',
  path: '/focus/repo/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/focus/repo/$owner/$repo.lazy').then((d) => d.Route),
)
const FocusOrgOrgReleasesRoute = FocusOrgOrgReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => FocusOrgOrgRoute,
} as any).lazy(() =>
  import('./routes/focus/org/$org/releases.lazy').then((d) => d.Route),
)
const AdminJobsSubscriptionsTaskIdRoute =
  AdminJobsSubscriptionsTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AdminJobsSubscriptionsRoute,
  } as any).lazy(() =>
    import('./routes/admin/jobs/subscriptions/$taskId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminJobsTasksTaskIdRouteRoute =
  AdminJobsTasksTaskIdRouteRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AdminJobsRouteRoute,
  } as any)
const FocusRepoOwnerRepoIndexRoute = FocusRepoOwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FocusRepoOwnerRepoRoute,
} as any).lazy(() =>
  import('./routes/focus/repo/$owner/$repo/index.lazy').then((d) => d.Route),
)
const AdminJobsTasksTaskIdIndexRoute =
  AdminJobsTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminJobsTasksTaskIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/admin/jobs/tasks/$taskId/index.lazy').then((d) => d.Route),
  )
const FocusRepoOwnerRepoReleasesRoute =
  FocusRepoOwnerRepoReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => FocusRepoOwnerRepoRoute,
  } as any).lazy(() =>
    import('./routes/focus/repo/$owner/$repo/releases.lazy').then(
      (d) => d.Route,
    ),
  )
const OwnerRepoReleasesTagTagRoute = OwnerRepoReleasesTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => OwnerRepoReleasesRoute,
} as any).lazy(() =>
  import('./routes/$owner/$repo/releases/tag/$tag.lazy').then((d) => d.Route),
)
const PublicOwnerRepoReleasesTagTagRoute =
  PublicOwnerRepoReleasesTagTagRouteImport.update({
    id: '/public/$owner/$repo/releases/tag/$tag',
    path: '/public/$owner/$repo/releases/tag/$tag',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/public/$owner/$repo/releases/tag/$tag.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminJobsTasksTaskIdLlmCallIdRoute =
  AdminJobsTasksTaskIdLlmCallIdRouteImport.update({
    id: '/llm/$callId',
    path: '/llm/$callId',
    getParentRoute: () => AdminJobsTasksTaskIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/admin/jobs/tasks/$taskId/llm/$callId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/briefs': typeof BriefsRoute
  '/followers': typeof FollowersRoute
  '/inbox': typeof InboxRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/admin/jobs': typeof AdminJobsRouteRouteWithChildren
  '/admin/public-releases': typeof AdminPublicReleasesRoute
  '/admin/repos': typeof AdminReposRoute
  '/admin/users': typeof AdminUsersRoute
  '/bind/github': typeof BindGithubRoute
  '/focus/mine': typeof FocusMineRouteWithChildren
  '/focus/repos': typeof FocusReposRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/$owner/$repo/releases': typeof OwnerRepoReleasesRouteWithChildren
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/subscriptions': typeof AdminJobsSubscriptionsRouteWithChildren
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/focus/mine/releases': typeof FocusMineReleasesRoute
  '/focus/org/$org': typeof FocusOrgOrgRouteWithChildren
  '/focus/repos/releases': typeof FocusReposReleasesRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/focus/mine/': typeof FocusMineIndexRoute
  '/focus/repos/': typeof FocusReposIndexRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdRouteRouteWithChildren
  '/admin/jobs/subscriptions/$taskId': typeof AdminJobsSubscriptionsTaskIdRoute
  '/focus/org/$org/releases': typeof FocusOrgOrgReleasesRoute
  '/focus/repo/$owner/$repo': typeof FocusRepoOwnerRepoRouteWithChildren
  '/$owner/$repo/releases/': typeof OwnerRepoReleasesIndexRoute
  '/focus/org/$org/': typeof FocusOrgOrgIndexRoute
  '/$owner/$repo/releases/tag/$tag': typeof OwnerRepoReleasesTagTagRoute
  '/focus/repo/$owner/$repo/releases': typeof FocusRepoOwnerRepoReleasesRoute
  '/admin/jobs/tasks/$taskId/': typeof AdminJobsTasksTaskIdIndexRoute
  '/focus/repo/$owner/$repo/': typeof FocusRepoOwnerRepoIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
  '/public/$owner/$repo/releases/tag/$tag': typeof PublicOwnerRepoReleasesTagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/followers': typeof FollowersRoute
  '/inbox': typeof InboxRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/admin/public-releases': typeof AdminPublicReleasesRoute
  '/admin/repos': typeof AdminReposRoute
  '/admin/users': typeof AdminUsersRoute
  '/bind/github': typeof BindGithubRoute
  '/admin': typeof AdminIndexRoute
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/subscriptions': typeof AdminJobsSubscriptionsRouteWithChildren
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/focus/mine/releases': typeof FocusMineReleasesRoute
  '/focus/repos/releases': typeof FocusReposReleasesRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/focus/mine': typeof FocusMineIndexRoute
  '/focus/repos': typeof FocusReposIndexRoute
  '/admin/jobs/subscriptions/$taskId': typeof AdminJobsSubscriptionsTaskIdRoute
  '/focus/org/$org/releases': typeof FocusOrgOrgReleasesRoute
  '/$owner/$repo/releases': typeof OwnerRepoReleasesIndexRoute
  '/focus/org/$org': typeof FocusOrgOrgIndexRoute
  '/$owner/$repo/releases/tag/$tag': typeof OwnerRepoReleasesTagTagRoute
  '/focus/repo/$owner/$repo/releases': typeof FocusRepoOwnerRepoReleasesRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdIndexRoute
  '/focus/repo/$owner/$repo': typeof FocusRepoOwnerRepoIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
  '/public/$owner/$repo/releases/tag/$tag': typeof PublicOwnerRepoReleasesTagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/briefs': typeof BriefsRoute
  '/followers': typeof FollowersRoute
  '/inbox': typeof InboxRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/admin/jobs': typeof AdminJobsRouteRouteWithChildren
  '/admin/public-releases': typeof AdminPublicReleasesRoute
  '/admin/repos': typeof AdminReposRoute
  '/admin/users': typeof AdminUsersRoute
  '/bind/github': typeof BindGithubRoute
  '/focus/mine': typeof FocusMineRouteWithChildren
  '/focus/repos': typeof FocusReposRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/$owner/$repo/releases': typeof OwnerRepoReleasesRouteWithChildren
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/subscriptions': typeof AdminJobsSubscriptionsRouteWithChildren
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/focus/mine/releases': typeof FocusMineReleasesRoute
  '/focus/org/$org': typeof FocusOrgOrgRouteWithChildren
  '/focus/repos/releases': typeof FocusReposReleasesRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/focus/mine/': typeof FocusMineIndexRoute
  '/focus/repos/': typeof FocusReposIndexRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdRouteRouteWithChildren
  '/admin/jobs/subscriptions/$taskId': typeof AdminJobsSubscriptionsTaskIdRoute
  '/focus/org/$org/releases': typeof FocusOrgOrgReleasesRoute
  '/focus/repo/$owner/$repo': typeof FocusRepoOwnerRepoRouteWithChildren
  '/$owner/$repo/releases/': typeof OwnerRepoReleasesIndexRoute
  '/focus/org/$org/': typeof FocusOrgOrgIndexRoute
  '/$owner/$repo/releases/tag/$tag': typeof OwnerRepoReleasesTagTagRoute
  '/focus/repo/$owner/$repo/releases': typeof FocusRepoOwnerRepoReleasesRoute
  '/admin/jobs/tasks/$taskId/': typeof AdminJobsTasksTaskIdIndexRoute
  '/focus/repo/$owner/$repo/': typeof FocusRepoOwnerRepoIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
  '/public/$owner/$repo/releases/tag/$tag': typeof PublicOwnerRepoReleasesTagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/briefs'
    | '/followers'
    | '/inbox'
    | '/releases'
    | '/settings'
    | '/stars'
    | '/admin/jobs'
    | '/admin/public-releases'
    | '/admin/repos'
    | '/admin/users'
    | '/bind/github'
    | '/focus/mine'
    | '/focus/repos'
    | '/admin/'
    | '/$owner/$repo/releases'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/subscriptions'
    | '/admin/jobs/translations'
    | '/focus/mine/releases'
    | '/focus/org/$org'
    | '/focus/repos/releases'
    | '/admin/jobs/'
    | '/focus/mine/'
    | '/focus/repos/'
    | '/admin/jobs/tasks/$taskId'
    | '/admin/jobs/subscriptions/$taskId'
    | '/focus/org/$org/releases'
    | '/focus/repo/$owner/$repo'
    | '/$owner/$repo/releases/'
    | '/focus/org/$org/'
    | '/$owner/$repo/releases/tag/$tag'
    | '/focus/repo/$owner/$repo/releases'
    | '/admin/jobs/tasks/$taskId/'
    | '/focus/repo/$owner/$repo/'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
    | '/public/$owner/$repo/releases/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefs'
    | '/followers'
    | '/inbox'
    | '/releases'
    | '/settings'
    | '/stars'
    | '/admin/public-releases'
    | '/admin/repos'
    | '/admin/users'
    | '/bind/github'
    | '/admin'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/subscriptions'
    | '/admin/jobs/translations'
    | '/focus/mine/releases'
    | '/focus/repos/releases'
    | '/admin/jobs'
    | '/focus/mine'
    | '/focus/repos'
    | '/admin/jobs/subscriptions/$taskId'
    | '/focus/org/$org/releases'
    | '/$owner/$repo/releases'
    | '/focus/org/$org'
    | '/$owner/$repo/releases/tag/$tag'
    | '/focus/repo/$owner/$repo/releases'
    | '/admin/jobs/tasks/$taskId'
    | '/focus/repo/$owner/$repo'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
    | '/public/$owner/$repo/releases/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/briefs'
    | '/followers'
    | '/inbox'
    | '/releases'
    | '/settings'
    | '/stars'
    | '/admin/jobs'
    | '/admin/public-releases'
    | '/admin/repos'
    | '/admin/users'
    | '/bind/github'
    | '/focus/mine'
    | '/focus/repos'
    | '/admin/'
    | '/$owner/$repo/releases'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/subscriptions'
    | '/admin/jobs/translations'
    | '/focus/mine/releases'
    | '/focus/org/$org'
    | '/focus/repos/releases'
    | '/admin/jobs/'
    | '/focus/mine/'
    | '/focus/repos/'
    | '/admin/jobs/tasks/$taskId'
    | '/admin/jobs/subscriptions/$taskId'
    | '/focus/org/$org/releases'
    | '/focus/repo/$owner/$repo'
    | '/$owner/$repo/releases/'
    | '/focus/org/$org/'
    | '/$owner/$repo/releases/tag/$tag'
    | '/focus/repo/$owner/$repo/releases'
    | '/admin/jobs/tasks/$taskId/'
    | '/focus/repo/$owner/$repo/'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
    | '/public/$owner/$repo/releases/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BriefsRoute: typeof BriefsRoute
  FollowersRoute: typeof FollowersRoute
  InboxRoute: typeof InboxRoute
  ReleasesRoute: typeof ReleasesRoute
  SettingsRoute: typeof SettingsRoute
  StarsRoute: typeof StarsRoute
  BindGithubRoute: typeof BindGithubRoute
  FocusMineRoute: typeof FocusMineRouteWithChildren
  FocusReposRoute: typeof FocusReposRouteWithChildren
  OwnerRepoReleasesRoute: typeof OwnerRepoReleasesRouteWithChildren
  FocusOrgOrgRoute: typeof FocusOrgOrgRouteWithChildren
  FocusRepoOwnerRepoRoute: typeof FocusRepoOwnerRepoRouteWithChildren
  PublicOwnerRepoReleasesTagTagRoute: typeof PublicOwnerRepoReleasesTagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers': {
      id: '/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/focus/repos': {
      id: '/focus/repos'
      path: '/focus/repos'
      fullPath: '/focus/repos'
      preLoaderRoute: typeof FocusReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/mine': {
      id: '/focus/mine'
      path: '/focus/mine'
      fullPath: '/focus/mine'
      preLoaderRoute: typeof FocusMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bind/github': {
      id: '/bind/github'
      path: '/bind/github'
      fullPath: '/bind/github'
      preLoaderRoute: typeof BindGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/repos': {
      id: '/admin/repos'
      path: '/repos'
      fullPath: '/admin/repos'
      preLoaderRoute: typeof AdminReposRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/public-releases': {
      id: '/admin/public-releases'
      path: '/public-releases'
      fullPath: '/admin/public-releases'
      preLoaderRoute: typeof AdminPublicReleasesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/focus/repos/': {
      id: '/focus/repos/'
      path: '/'
      fullPath: '/focus/repos/'
      preLoaderRoute: typeof FocusReposIndexRouteImport
      parentRoute: typeof FocusReposRoute
    }
    '/focus/mine/': {
      id: '/focus/mine/'
      path: '/'
      fullPath: '/focus/mine/'
      preLoaderRoute: typeof FocusMineIndexRouteImport
      parentRoute: typeof FocusMineRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/focus/repos/releases': {
      id: '/focus/repos/releases'
      path: '/releases'
      fullPath: '/focus/repos/releases'
      preLoaderRoute: typeof FocusReposReleasesRouteImport
      parentRoute: typeof FocusReposRoute
    }
    '/focus/org/$org': {
      id: '/focus/org/$org'
      path: '/focus/org/$org'
      fullPath: '/focus/org/$org'
      preLoaderRoute: typeof FocusOrgOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/mine/releases': {
      id: '/focus/mine/releases'
      path: '/releases'
      fullPath: '/focus/mine/releases'
      preLoaderRoute: typeof FocusMineReleasesRouteImport
      parentRoute: typeof FocusMineRoute
    }
    '/admin/jobs/translations': {
      id: '/admin/jobs/translations'
      path: '/translations'
      fullPath: '/admin/jobs/translations'
      preLoaderRoute: typeof AdminJobsTranslationsRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/subscriptions': {
      id: '/admin/jobs/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/jobs/subscriptions'
      preLoaderRoute: typeof AdminJobsSubscriptionsRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/scheduled': {
      id: '/admin/jobs/scheduled'
      path: '/scheduled'
      fullPath: '/admin/jobs/scheduled'
      preLoaderRoute: typeof AdminJobsScheduledRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/llm': {
      id: '/admin/jobs/llm'
      path: '/llm'
      fullPath: '/admin/jobs/llm'
      preLoaderRoute: typeof AdminJobsLlmRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/$owner/$repo/releases': {
      id: '/$owner/$repo/releases'
      path: '/$owner/$repo/releases'
      fullPath: '/$owner/$repo/releases'
      preLoaderRoute: typeof OwnerRepoReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/org/$org/': {
      id: '/focus/org/$org/'
      path: '/'
      fullPath: '/focus/org/$org/'
      preLoaderRoute: typeof FocusOrgOrgIndexRouteImport
      parentRoute: typeof FocusOrgOrgRoute
    }
    '/$owner/$repo/releases/': {
      id: '/$owner/$repo/releases/'
      path: '/'
      fullPath: '/$owner/$repo/releases/'
      preLoaderRoute: typeof OwnerRepoReleasesIndexRouteImport
      parentRoute: typeof OwnerRepoReleasesRoute
    }
    '/focus/repo/$owner/$repo': {
      id: '/focus/repo/$owner/$repo'
      path: '/focus/repo/$owner/$repo'
      fullPath: '/focus/repo/$owner/$repo'
      preLoaderRoute: typeof FocusRepoOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/org/$org/releases': {
      id: '/focus/org/$org/releases'
      path: '/releases'
      fullPath: '/focus/org/$org/releases'
      preLoaderRoute: typeof FocusOrgOrgReleasesRouteImport
      parentRoute: typeof FocusOrgOrgRoute
    }
    '/admin/jobs/subscriptions/$taskId': {
      id: '/admin/jobs/subscriptions/$taskId'
      path: '/$taskId'
      fullPath: '/admin/jobs/subscriptions/$taskId'
      preLoaderRoute: typeof AdminJobsSubscriptionsTaskIdRouteImport
      parentRoute: typeof AdminJobsSubscriptionsRoute
    }
    '/admin/jobs/tasks/$taskId': {
      id: '/admin/jobs/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/admin/jobs/tasks/$taskId'
      preLoaderRoute: typeof AdminJobsTasksTaskIdRouteRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/focus/repo/$owner/$repo/': {
      id: '/focus/repo/$owner/$repo/'
      path: '/'
      fullPath: '/focus/repo/$owner/$repo/'
      preLoaderRoute: typeof FocusRepoOwnerRepoIndexRouteImport
      parentRoute: typeof FocusRepoOwnerRepoRoute
    }
    '/admin/jobs/tasks/$taskId/': {
      id: '/admin/jobs/tasks/$taskId/'
      path: '/'
      fullPath: '/admin/jobs/tasks/$taskId/'
      preLoaderRoute: typeof AdminJobsTasksTaskIdIndexRouteImport
      parentRoute: typeof AdminJobsTasksTaskIdRouteRoute
    }
    '/focus/repo/$owner/$repo/releases': {
      id: '/focus/repo/$owner/$repo/releases'
      path: '/releases'
      fullPath: '/focus/repo/$owner/$repo/releases'
      preLoaderRoute: typeof FocusRepoOwnerRepoReleasesRouteImport
      parentRoute: typeof FocusRepoOwnerRepoRoute
    }
    '/$owner/$repo/releases/tag/$tag': {
      id: '/$owner/$repo/releases/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/$owner/$repo/releases/tag/$tag'
      preLoaderRoute: typeof OwnerRepoReleasesTagTagRouteImport
      parentRoute: typeof OwnerRepoReleasesRoute
    }
    '/public/$owner/$repo/releases/tag/$tag': {
      id: '/public/$owner/$repo/releases/tag/$tag'
      path: '/public/$owner/$repo/releases/tag/$tag'
      fullPath: '/public/$owner/$repo/releases/tag/$tag'
      preLoaderRoute: typeof PublicOwnerRepoReleasesTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/tasks/$taskId/llm/$callId': {
      id: '/admin/jobs/tasks/$taskId/llm/$callId'
      path: '/llm/$callId'
      fullPath: '/admin/jobs/tasks/$taskId/llm/$callId'
      preLoaderRoute: typeof AdminJobsTasksTaskIdLlmCallIdRouteImport
      parentRoute: typeof AdminJobsTasksTaskIdRouteRoute
    }
  }
}

interface AdminJobsSubscriptionsRouteChildren {
  AdminJobsSubscriptionsTaskIdRoute: typeof AdminJobsSubscriptionsTaskIdRoute
}

const AdminJobsSubscriptionsRouteChildren: AdminJobsSubscriptionsRouteChildren =
  {
    AdminJobsSubscriptionsTaskIdRoute: AdminJobsSubscriptionsTaskIdRoute,
  }

const AdminJobsSubscriptionsRouteWithChildren =
  AdminJobsSubscriptionsRoute._addFileChildren(
    AdminJobsSubscriptionsRouteChildren,
  )

interface AdminJobsTasksTaskIdRouteRouteChildren {
  AdminJobsTasksTaskIdIndexRoute: typeof AdminJobsTasksTaskIdIndexRoute
  AdminJobsTasksTaskIdLlmCallIdRoute: typeof AdminJobsTasksTaskIdLlmCallIdRoute
}

const AdminJobsTasksTaskIdRouteRouteChildren: AdminJobsTasksTaskIdRouteRouteChildren =
  {
    AdminJobsTasksTaskIdIndexRoute: AdminJobsTasksTaskIdIndexRoute,
    AdminJobsTasksTaskIdLlmCallIdRoute: AdminJobsTasksTaskIdLlmCallIdRoute,
  }

const AdminJobsTasksTaskIdRouteRouteWithChildren =
  AdminJobsTasksTaskIdRouteRoute._addFileChildren(
    AdminJobsTasksTaskIdRouteRouteChildren,
  )

interface AdminJobsRouteRouteChildren {
  AdminJobsLlmRoute: typeof AdminJobsLlmRoute
  AdminJobsScheduledRoute: typeof AdminJobsScheduledRoute
  AdminJobsSubscriptionsRoute: typeof AdminJobsSubscriptionsRouteWithChildren
  AdminJobsTranslationsRoute: typeof AdminJobsTranslationsRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminJobsTasksTaskIdRouteRoute: typeof AdminJobsTasksTaskIdRouteRouteWithChildren
}

const AdminJobsRouteRouteChildren: AdminJobsRouteRouteChildren = {
  AdminJobsLlmRoute: AdminJobsLlmRoute,
  AdminJobsScheduledRoute: AdminJobsScheduledRoute,
  AdminJobsSubscriptionsRoute: AdminJobsSubscriptionsRouteWithChildren,
  AdminJobsTranslationsRoute: AdminJobsTranslationsRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminJobsTasksTaskIdRouteRoute: AdminJobsTasksTaskIdRouteRouteWithChildren,
}

const AdminJobsRouteRouteWithChildren = AdminJobsRouteRoute._addFileChildren(
  AdminJobsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminJobsRouteRoute: typeof AdminJobsRouteRouteWithChildren
  AdminPublicReleasesRoute: typeof AdminPublicReleasesRoute
  AdminReposRoute: typeof AdminReposRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminJobsRouteRoute: AdminJobsRouteRouteWithChildren,
  AdminPublicReleasesRoute: AdminPublicReleasesRoute,
  AdminReposRoute: AdminReposRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface FocusMineRouteChildren {
  FocusMineReleasesRoute: typeof FocusMineReleasesRoute
  FocusMineIndexRoute: typeof FocusMineIndexRoute
}

const FocusMineRouteChildren: FocusMineRouteChildren = {
  FocusMineReleasesRoute: FocusMineReleasesRoute,
  FocusMineIndexRoute: FocusMineIndexRoute,
}

const FocusMineRouteWithChildren = FocusMineRoute._addFileChildren(
  FocusMineRouteChildren,
)

interface FocusReposRouteChildren {
  FocusReposReleasesRoute: typeof FocusReposReleasesRoute
  FocusReposIndexRoute: typeof FocusReposIndexRoute
}

const FocusReposRouteChildren: FocusReposRouteChildren = {
  FocusReposReleasesRoute: FocusReposReleasesRoute,
  FocusReposIndexRoute: FocusReposIndexRoute,
}

const FocusReposRouteWithChildren = FocusReposRoute._addFileChildren(
  FocusReposRouteChildren,
)

interface OwnerRepoReleasesRouteChildren {
  OwnerRepoReleasesIndexRoute: typeof OwnerRepoReleasesIndexRoute
  OwnerRepoReleasesTagTagRoute: typeof OwnerRepoReleasesTagTagRoute
}

const OwnerRepoReleasesRouteChildren: OwnerRepoReleasesRouteChildren = {
  OwnerRepoReleasesIndexRoute: OwnerRepoReleasesIndexRoute,
  OwnerRepoReleasesTagTagRoute: OwnerRepoReleasesTagTagRoute,
}

const OwnerRepoReleasesRouteWithChildren =
  OwnerRepoReleasesRoute._addFileChildren(OwnerRepoReleasesRouteChildren)

interface FocusOrgOrgRouteChildren {
  FocusOrgOrgReleasesRoute: typeof FocusOrgOrgReleasesRoute
  FocusOrgOrgIndexRoute: typeof FocusOrgOrgIndexRoute
}

const FocusOrgOrgRouteChildren: FocusOrgOrgRouteChildren = {
  FocusOrgOrgReleasesRoute: FocusOrgOrgReleasesRoute,
  FocusOrgOrgIndexRoute: FocusOrgOrgIndexRoute,
}

const FocusOrgOrgRouteWithChildren = FocusOrgOrgRoute._addFileChildren(
  FocusOrgOrgRouteChildren,
)

interface FocusRepoOwnerRepoRouteChildren {
  FocusRepoOwnerRepoReleasesRoute: typeof FocusRepoOwnerRepoReleasesRoute
  FocusRepoOwnerRepoIndexRoute: typeof FocusRepoOwnerRepoIndexRoute
}

const FocusRepoOwnerRepoRouteChildren: FocusRepoOwnerRepoRouteChildren = {
  FocusRepoOwnerRepoReleasesRoute: FocusRepoOwnerRepoReleasesRoute,
  FocusRepoOwnerRepoIndexRoute: FocusRepoOwnerRepoIndexRoute,
}

const FocusRepoOwnerRepoRouteWithChildren =
  FocusRepoOwnerRepoRoute._addFileChildren(FocusRepoOwnerRepoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BriefsRoute: BriefsRoute,
  FollowersRoute: FollowersRoute,
  InboxRoute: InboxRoute,
  ReleasesRoute: ReleasesRoute,
  SettingsRoute: SettingsRoute,
  StarsRoute: StarsRoute,
  BindGithubRoute: BindGithubRoute,
  FocusMineRoute: FocusMineRouteWithChildren,
  FocusReposRoute: FocusReposRouteWithChildren,
  OwnerRepoReleasesRoute: OwnerRepoReleasesRouteWithChildren,
  FocusOrgOrgRoute: FocusOrgOrgRouteWithChildren,
  FocusRepoOwnerRepoRoute: FocusRepoOwnerRepoRouteWithChildren,
  PublicOwnerRepoReleasesTagTagRoute: PublicOwnerRepoReleasesTagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
