/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminJobsRouteRouteImport } from './routes/admin/jobs/route'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminJobsTranslationsRouteImport } from './routes/admin/jobs/translations'
import { Route as AdminJobsScheduledRouteImport } from './routes/admin/jobs/scheduled'
import { Route as AdminJobsLlmRouteImport } from './routes/admin/jobs/llm'
import { Route as AdminJobsTasksTaskIdRouteRouteImport } from './routes/admin/jobs/tasks/$taskId/route'
import { Route as AdminJobsTasksTaskIdIndexRouteImport } from './routes/admin/jobs/tasks/$taskId/index'
import { Route as AdminJobsTasksTaskIdLlmCallIdRouteImport } from './routes/admin/jobs/tasks/$taskId/llm/$callId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRouteRoute = AdminJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminJobsRouteRoute,
} as any)
const AdminJobsTranslationsRoute = AdminJobsTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminJobsRouteRoute,
} as any)
const AdminJobsScheduledRoute = AdminJobsScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AdminJobsRouteRoute,
} as any)
const AdminJobsLlmRoute = AdminJobsLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AdminJobsRouteRoute,
} as any)
const AdminJobsTasksTaskIdRouteRoute =
  AdminJobsTasksTaskIdRouteRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AdminJobsRouteRoute,
  } as any)
const AdminJobsTasksTaskIdIndexRoute =
  AdminJobsTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminJobsTasksTaskIdRouteRoute,
  } as any)
const AdminJobsTasksTaskIdLlmCallIdRoute =
  AdminJobsTasksTaskIdLlmCallIdRouteImport.update({
    id: '/llm/$callId',
    path: '/llm/$callId',
    getParentRoute: () => AdminJobsTasksTaskIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/jobs': typeof AdminJobsRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdRouteRouteWithChildren
  '/admin/jobs/tasks/$taskId/': typeof AdminJobsTasksTaskIdIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/jobs': typeof AdminJobsRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdRouteRouteWithChildren
  '/admin/jobs/tasks/$taskId/': typeof AdminJobsTasksTaskIdIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/admin/jobs'
    | '/admin/'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/translations'
    | '/admin/jobs/'
    | '/admin/jobs/tasks/$taskId'
    | '/admin/jobs/tasks/$taskId/'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/admin'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/translations'
    | '/admin/jobs'
    | '/admin/jobs/tasks/$taskId'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/settings'
    | '/admin/jobs'
    | '/admin/'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/translations'
    | '/admin/jobs/'
    | '/admin/jobs/tasks/$taskId'
    | '/admin/jobs/tasks/$taskId/'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/translations': {
      id: '/admin/jobs/translations'
      path: '/translations'
      fullPath: '/admin/jobs/translations'
      preLoaderRoute: typeof AdminJobsTranslationsRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/scheduled': {
      id: '/admin/jobs/scheduled'
      path: '/scheduled'
      fullPath: '/admin/jobs/scheduled'
      preLoaderRoute: typeof AdminJobsScheduledRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/llm': {
      id: '/admin/jobs/llm'
      path: '/llm'
      fullPath: '/admin/jobs/llm'
      preLoaderRoute: typeof AdminJobsLlmRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/tasks/$taskId': {
      id: '/admin/jobs/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/admin/jobs/tasks/$taskId'
      preLoaderRoute: typeof AdminJobsTasksTaskIdRouteRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/tasks/$taskId/': {
      id: '/admin/jobs/tasks/$taskId/'
      path: '/'
      fullPath: '/admin/jobs/tasks/$taskId/'
      preLoaderRoute: typeof AdminJobsTasksTaskIdIndexRouteImport
      parentRoute: typeof AdminJobsTasksTaskIdRouteRoute
    }
    '/admin/jobs/tasks/$taskId/llm/$callId': {
      id: '/admin/jobs/tasks/$taskId/llm/$callId'
      path: '/llm/$callId'
      fullPath: '/admin/jobs/tasks/$taskId/llm/$callId'
      preLoaderRoute: typeof AdminJobsTasksTaskIdLlmCallIdRouteImport
      parentRoute: typeof AdminJobsTasksTaskIdRouteRoute
    }
  }
}

interface AdminJobsTasksTaskIdRouteRouteChildren {
  AdminJobsTasksTaskIdIndexRoute: typeof AdminJobsTasksTaskIdIndexRoute
  AdminJobsTasksTaskIdLlmCallIdRoute: typeof AdminJobsTasksTaskIdLlmCallIdRoute
}

const AdminJobsTasksTaskIdRouteRouteChildren: AdminJobsTasksTaskIdRouteRouteChildren =
  {
    AdminJobsTasksTaskIdIndexRoute: AdminJobsTasksTaskIdIndexRoute,
    AdminJobsTasksTaskIdLlmCallIdRoute: AdminJobsTasksTaskIdLlmCallIdRoute,
  }

const AdminJobsTasksTaskIdRouteRouteWithChildren =
  AdminJobsTasksTaskIdRouteRoute._addFileChildren(
    AdminJobsTasksTaskIdRouteRouteChildren,
  )

interface AdminJobsRouteRouteChildren {
  AdminJobsLlmRoute: typeof AdminJobsLlmRoute
  AdminJobsScheduledRoute: typeof AdminJobsScheduledRoute
  AdminJobsTranslationsRoute: typeof AdminJobsTranslationsRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminJobsTasksTaskIdRouteRoute: typeof AdminJobsTasksTaskIdRouteRouteWithChildren
}

const AdminJobsRouteRouteChildren: AdminJobsRouteRouteChildren = {
  AdminJobsLlmRoute: AdminJobsLlmRoute,
  AdminJobsScheduledRoute: AdminJobsScheduledRoute,
  AdminJobsTranslationsRoute: AdminJobsTranslationsRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminJobsTasksTaskIdRouteRoute: AdminJobsTasksTaskIdRouteRouteWithChildren,
}

const AdminJobsRouteRouteWithChildren = AdminJobsRouteRoute._addFileChildren(
  AdminJobsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminJobsRouteRoute: typeof AdminJobsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminJobsRouteRoute: AdminJobsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
