/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FollowersRouteImport } from './routes/followers'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BindGithubRouteImport } from './routes/bind/github'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminJobsRouteRouteImport } from './routes/admin/jobs/route'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminJobsTranslationsRouteImport } from './routes/admin/jobs/translations'
import { Route as AdminJobsScheduledRouteImport } from './routes/admin/jobs/scheduled'
import { Route as AdminJobsLlmRouteImport } from './routes/admin/jobs/llm'
import { Route as AdminJobsTasksTaskIdRouteRouteImport } from './routes/admin/jobs/tasks/$taskId/route'
import { Route as AdminJobsTasksTaskIdIndexRouteImport } from './routes/admin/jobs/tasks/$taskId/index'
import { Route as OwnerRepoReleasesTagTagRouteImport } from './routes/$owner/$repo/releases/tag/$tag'
import { Route as AdminJobsTasksTaskIdLlmCallIdRouteImport } from './routes/admin/jobs/tasks/$taskId/llm/$callId'

const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/stars.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/releases.lazy').then((d) => d.Route))
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/inbox.lazy').then((d) => d.Route))
const FollowersRoute = FollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/followers.lazy').then((d) => d.Route))
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/briefs.lazy').then((d) => d.Route))
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const BindGithubRoute = BindGithubRouteImport.update({
  id: '/bind/github',
  path: '/bind/github',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bind/github.lazy').then((d) => d.Route))
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/users.lazy').then((d) => d.Route))
const AdminJobsRouteRoute = AdminJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/index.lazy').then((d) => d.Route),
)
const AdminJobsTranslationsRoute = AdminJobsTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/translations.lazy').then((d) => d.Route),
)
const AdminJobsScheduledRoute = AdminJobsScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/scheduled.lazy').then((d) => d.Route),
)
const AdminJobsLlmRoute = AdminJobsLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AdminJobsRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/jobs/llm.lazy').then((d) => d.Route),
)
const AdminJobsTasksTaskIdRouteRoute =
  AdminJobsTasksTaskIdRouteRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AdminJobsRouteRoute,
  } as any)
const AdminJobsTasksTaskIdIndexRoute =
  AdminJobsTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminJobsTasksTaskIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/admin/jobs/tasks/$taskId/index.lazy').then((d) => d.Route),
  )
const OwnerRepoReleasesTagTagRoute = OwnerRepoReleasesTagTagRouteImport.update({
  id: '/$owner/$repo/releases/tag/$tag',
  path: '/$owner/$repo/releases/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$owner/$repo/releases/tag/$tag.lazy').then((d) => d.Route),
)
const AdminJobsTasksTaskIdLlmCallIdRoute =
  AdminJobsTasksTaskIdLlmCallIdRouteImport.update({
    id: '/llm/$callId',
    path: '/llm/$callId',
    getParentRoute: () => AdminJobsTasksTaskIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/admin/jobs/tasks/$taskId/llm/$callId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/briefs': typeof BriefsRoute
  '/followers': typeof FollowersRoute
  '/inbox': typeof InboxRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/admin/jobs': typeof AdminJobsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/bind/github': typeof BindGithubRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdRouteRouteWithChildren
  '/$owner/$repo/releases/tag/$tag': typeof OwnerRepoReleasesTagTagRoute
  '/admin/jobs/tasks/$taskId/': typeof AdminJobsTasksTaskIdIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/followers': typeof FollowersRoute
  '/inbox': typeof InboxRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/admin/users': typeof AdminUsersRoute
  '/bind/github': typeof BindGithubRoute
  '/admin': typeof AdminIndexRoute
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/$owner/$repo/releases/tag/$tag': typeof OwnerRepoReleasesTagTagRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/briefs': typeof BriefsRoute
  '/followers': typeof FollowersRoute
  '/inbox': typeof InboxRoute
  '/releases': typeof ReleasesRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/admin/jobs': typeof AdminJobsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/bind/github': typeof BindGithubRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jobs/llm': typeof AdminJobsLlmRoute
  '/admin/jobs/scheduled': typeof AdminJobsScheduledRoute
  '/admin/jobs/translations': typeof AdminJobsTranslationsRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/jobs/tasks/$taskId': typeof AdminJobsTasksTaskIdRouteRouteWithChildren
  '/$owner/$repo/releases/tag/$tag': typeof OwnerRepoReleasesTagTagRoute
  '/admin/jobs/tasks/$taskId/': typeof AdminJobsTasksTaskIdIndexRoute
  '/admin/jobs/tasks/$taskId/llm/$callId': typeof AdminJobsTasksTaskIdLlmCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/briefs'
    | '/followers'
    | '/inbox'
    | '/releases'
    | '/settings'
    | '/stars'
    | '/admin/jobs'
    | '/admin/users'
    | '/bind/github'
    | '/admin/'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/translations'
    | '/admin/jobs/'
    | '/admin/jobs/tasks/$taskId'
    | '/$owner/$repo/releases/tag/$tag'
    | '/admin/jobs/tasks/$taskId/'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefs'
    | '/followers'
    | '/inbox'
    | '/releases'
    | '/settings'
    | '/stars'
    | '/admin/users'
    | '/bind/github'
    | '/admin'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/translations'
    | '/admin/jobs'
    | '/$owner/$repo/releases/tag/$tag'
    | '/admin/jobs/tasks/$taskId'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/briefs'
    | '/followers'
    | '/inbox'
    | '/releases'
    | '/settings'
    | '/stars'
    | '/admin/jobs'
    | '/admin/users'
    | '/bind/github'
    | '/admin/'
    | '/admin/jobs/llm'
    | '/admin/jobs/scheduled'
    | '/admin/jobs/translations'
    | '/admin/jobs/'
    | '/admin/jobs/tasks/$taskId'
    | '/$owner/$repo/releases/tag/$tag'
    | '/admin/jobs/tasks/$taskId/'
    | '/admin/jobs/tasks/$taskId/llm/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BriefsRoute: typeof BriefsRoute
  FollowersRoute: typeof FollowersRoute
  InboxRoute: typeof InboxRoute
  ReleasesRoute: typeof ReleasesRoute
  SettingsRoute: typeof SettingsRoute
  StarsRoute: typeof StarsRoute
  BindGithubRoute: typeof BindGithubRoute
  OwnerRepoReleasesTagTagRoute: typeof OwnerRepoReleasesTagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers': {
      id: '/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/bind/github': {
      id: '/bind/github'
      path: '/bind/github'
      fullPath: '/bind/github'
      preLoaderRoute: typeof BindGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/translations': {
      id: '/admin/jobs/translations'
      path: '/translations'
      fullPath: '/admin/jobs/translations'
      preLoaderRoute: typeof AdminJobsTranslationsRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/scheduled': {
      id: '/admin/jobs/scheduled'
      path: '/scheduled'
      fullPath: '/admin/jobs/scheduled'
      preLoaderRoute: typeof AdminJobsScheduledRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/llm': {
      id: '/admin/jobs/llm'
      path: '/llm'
      fullPath: '/admin/jobs/llm'
      preLoaderRoute: typeof AdminJobsLlmRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/tasks/$taskId': {
      id: '/admin/jobs/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/admin/jobs/tasks/$taskId'
      preLoaderRoute: typeof AdminJobsTasksTaskIdRouteRouteImport
      parentRoute: typeof AdminJobsRouteRoute
    }
    '/admin/jobs/tasks/$taskId/': {
      id: '/admin/jobs/tasks/$taskId/'
      path: '/'
      fullPath: '/admin/jobs/tasks/$taskId/'
      preLoaderRoute: typeof AdminJobsTasksTaskIdIndexRouteImport
      parentRoute: typeof AdminJobsTasksTaskIdRouteRoute
    }
    '/$owner/$repo/releases/tag/$tag': {
      id: '/$owner/$repo/releases/tag/$tag'
      path: '/$owner/$repo/releases/tag/$tag'
      fullPath: '/$owner/$repo/releases/tag/$tag'
      preLoaderRoute: typeof OwnerRepoReleasesTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/tasks/$taskId/llm/$callId': {
      id: '/admin/jobs/tasks/$taskId/llm/$callId'
      path: '/llm/$callId'
      fullPath: '/admin/jobs/tasks/$taskId/llm/$callId'
      preLoaderRoute: typeof AdminJobsTasksTaskIdLlmCallIdRouteImport
      parentRoute: typeof AdminJobsTasksTaskIdRouteRoute
    }
  }
}

interface AdminJobsTasksTaskIdRouteRouteChildren {
  AdminJobsTasksTaskIdIndexRoute: typeof AdminJobsTasksTaskIdIndexRoute
  AdminJobsTasksTaskIdLlmCallIdRoute: typeof AdminJobsTasksTaskIdLlmCallIdRoute
}

const AdminJobsTasksTaskIdRouteRouteChildren: AdminJobsTasksTaskIdRouteRouteChildren =
  {
    AdminJobsTasksTaskIdIndexRoute: AdminJobsTasksTaskIdIndexRoute,
    AdminJobsTasksTaskIdLlmCallIdRoute: AdminJobsTasksTaskIdLlmCallIdRoute,
  }

const AdminJobsTasksTaskIdRouteRouteWithChildren =
  AdminJobsTasksTaskIdRouteRoute._addFileChildren(
    AdminJobsTasksTaskIdRouteRouteChildren,
  )

interface AdminJobsRouteRouteChildren {
  AdminJobsLlmRoute: typeof AdminJobsLlmRoute
  AdminJobsScheduledRoute: typeof AdminJobsScheduledRoute
  AdminJobsTranslationsRoute: typeof AdminJobsTranslationsRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminJobsTasksTaskIdRouteRoute: typeof AdminJobsTasksTaskIdRouteRouteWithChildren
}

const AdminJobsRouteRouteChildren: AdminJobsRouteRouteChildren = {
  AdminJobsLlmRoute: AdminJobsLlmRoute,
  AdminJobsScheduledRoute: AdminJobsScheduledRoute,
  AdminJobsTranslationsRoute: AdminJobsTranslationsRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminJobsTasksTaskIdRouteRoute: AdminJobsTasksTaskIdRouteRouteWithChildren,
}

const AdminJobsRouteRouteWithChildren = AdminJobsRouteRoute._addFileChildren(
  AdminJobsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminJobsRouteRoute: typeof AdminJobsRouteRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminJobsRouteRoute: AdminJobsRouteRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BriefsRoute: BriefsRoute,
  FollowersRoute: FollowersRoute,
  InboxRoute: InboxRoute,
  ReleasesRoute: ReleasesRoute,
  SettingsRoute: SettingsRoute,
  StarsRoute: StarsRoute,
  BindGithubRoute: BindGithubRoute,
  OwnerRepoReleasesTagTagRoute: OwnerRepoReleasesTagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
