export const DEMO_INSPECTOR_PANEL_WIDTH_PX = 380;
export const DEMO_INSPECTOR_DOCKED_COLUMN_GAP_PX = 24;
export const DEMO_APP_MAX_FRAME_WIDTH_PX = 1152;
export const DEMO_INSPECTOR_DOCKED_CONTENT_OFFSET_PX =
	DEMO_INSPECTOR_PANEL_WIDTH_PX + DEMO_INSPECTOR_DOCKED_COLUMN_GAP_PX;
export const DEMO_INSPECTOR_DOCKED_LAYOUT_WIDTH_PX =
	DEMO_INSPECTOR_DOCKED_CONTENT_OFFSET_PX + DEMO_APP_MAX_FRAME_WIDTH_PX;
export const DEMO_INSPECTOR_DOCKED_VIEWPORT_GUTTER_PX = 24;
export const DEMO_INSPECTOR_DOCKED_BREAKPOINT_PX =
	DEMO_INSPECTOR_DOCKED_LAYOUT_WIDTH_PX +
	DEMO_INSPECTOR_DOCKED_VIEWPORT_GUTTER_PX * 2;
